# Generated by Django 3.2.2 on 2021-05-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Слаг')),
                ('body', models.TextField(blank=True, db_index=True, verbose_name='Содержание')),
                ('date_pub', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
        ),
    ]
